[package]
name = "git-folder-sync"
version = "0.5.13"
edition = "2021"

[lib]
name = "git_folder_sync_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3" }

[dependencies]
tauri = { version = "2.11.4", features = [] }
tauri-plugin-dialog = "2.7.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
git2 = { version = "0.21", features = ["https", "vendored-openssl"] }
anyhow = "1"
keyring = { version = "4.2.0", default-features = false, features = ["v1", "android-native-keyring-store"] }
